name: Aggiorna dati calcio

on:
  schedule:
    # 10:00 Italia durante l'ora legale (CEST) = 08:00 UTC
    - cron: "0 8 * * *"
    # 10:00 Italia durante l'ora solare (CET) = 09:00 UTC
    - cron: "0 9 * * *"
    # 10:10 Italia durante l'ora legale (CEST) = 08:10 UTC
    - cron: "10 8 * * *"
    # 10:10 Italia durante l'ora solare (CET) = 09:10 UTC
    - cron: "10 9 * * *"
  workflow_dispatch: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      # Crea .env.local usando i secrets del repo
      - name: Create .env.local from secrets
        run: |
          rm -f .env.local
          {
            echo "API_FOOTBALL_KEY=${API_FOOTBALL_KEY}"
            echo "API_FOOTBALLDATA_KEY=${API_FOOTBALLDATA_KEY}"
            echo "API_SOCCERDATA_KEY=${API_SOCCERDATA_KEY}"
          } > .env.local
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALLDATA_KEY: ${{ secrets.API_FOOTBALLDATA_KEY }}
          API_SOCCERDATA_KEY: ${{ secrets.API_SOCCERDATA_KEY }}

      - name: Build Next
        run: npm run build

      - name: Start Next server
        run: |
          nohup npm start > server.log 2>&1 &
          echo "Avvio server..."
          sleep 15

      # --- 10:00 IT (08:00/09:00 UTC) ---
      - name: Run fetchData 10-00 IT
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 8 * * *' || github.event.schedule == '0 9 * * *' }}
        run: |
          echo ">>> fetchDataOrg"
          for league in italia francia germania spagna inghilterra portogallo olanda; do
            curl -fSs "http://localhost:3000/api/fetchDataOrg?league=$league&season=2025-2026"
          done

          echo ">>> fetchDataSoc"
          for league in turchia austria belgio danimarca grecia polonia romania svizzera ungheria; do
            curl -fSs "http://localhost:3000/api/fetchDataSoc?league=$league"
          done

      - name: Attendi 70s solo manuale
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: sleep 70

      # --- 10:10 IT (08:10/09:10 UTC) ---
      - name: Run fetchResult 10-10 IT
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '10 8 * * *' || github.event.schedule == '10 9 * * *' }}
        run: |
          echo ">>> fetchResultOrg"
          for league in italia francia germania spagna inghilterra portogallo olanda; do
            curl -fSs "http://localhost:3000/api/fetchResultOrg?league=$league&season=2025-2026"
          done

          echo ">>> fetchResultSoc"
          for league in turchia austria belgio danimarca grecia polonia romania svizzera ungheria; do
            curl -fSs "http://localhost:3000/api/fetchResultSoc?league=$league&season=2025-2026"
          done

      # Mostra sempre gli ultimi log del server (anche se un curl fallisce)
      - name: Log server Next (tail)
        if: ${{ always() }}
        run: |
          echo "=== tail server.log ==="
          tail -n 200 server.log || echo "server.log non trovato"

      - name: Diagnostica contenuto data e diff
        if: ${{ always() }}
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          find data -maxdepth 3 -type f -name "*.json" -print | sort || true
          echo "--- changed files ---"
          git status --porcelain

      - name: Commit JSON changes
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data
          if ! git diff --cached --quiet; then
            git commit -m "update: refresh dati JSON automatico (10:00/10:10 IT)"
            git push
          else
            echo "Nessuna modifica trovata."
          fi