name: Aggiorna dati calcio

on:
  schedule:
    - cron: "0 6 * * *"   # Sempre 08:00 IT (durante CEST)
    - cron: "0 7 * * *"   # Sempre 09:00 IT (durante CEST)
  workflow_dispatch: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: update-data-main
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      # Crea .env.local usando i secrets del repo
      - name: Create .env.local from secrets
        run: |
          rm -f .env.local
          {
            echo "API_FOOTBALL_KEY=${API_FOOTBALL_KEY}"
            echo "API_FOOTBALLDATA_KEY=${API_FOOTBALLDATA_KEY}"
            echo "API_SOCCERDATA_KEY=${API_SOCCERDATA_KEY}"
          } > .env.local
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALLDATA_KEY: ${{ secrets.API_FOOTBALLDATA_KEY }}
          API_SOCCERDATA_KEY: ${{ secrets.API_SOCCERDATA_KEY }}

      - name: Build Next
        run: npm run build

      - name: Start Next server
        run: |
          nohup npm start > server.log 2>&1 &
          echo "Avvio server..."
          sleep 15

# --- 08:00 IT (06:00 UTC) ---
      - name: Run fetchData 08-00 IT
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 6 * * *' }}
        run: |
          echo ">>> fetchDataOrg"
          for league in italia francia germania spagna inghilterra portogallo olanda; do
            curl -fSs "http://localhost:3000/api/fetchDataOrg?league=$league&season=2025-2026"
          done

          echo ">>> fetchDataSoc"
          for league in turchia austria belgio danimarca grecia polonia romania svizzera ungheria; do
            curl -fSs "http://localhost:3000/api/fetchDataSoc?league=$league"
          done

      - name: Attendi 70s solo manuale
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: sleep 70

# --- 09:00 IT (07:00 UTC) ---
      - name: Run fetchResult 09-00 IT
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.schedule == '0 7 * * *' }}
        run: |
          echo ">>> fetchResultOrg"
          for league in italia francia germania spagna inghilterra portogallo olanda; do
            echo "==> ORG $league"
            curl -fSs "http://localhost:3000/api/fetchResultOrg?league=$league&season=2025-2026"
            echo
            sleep 1
          done

          echo ">>> fetchResultSoc (con retry)"
          retry() {
            url="$1"
            tries=0
            until [ $tries -ge 3 ]
            do
              code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" "$url" || echo "000")
              echo "HTTP $code"
              cat /tmp/resp.json || true
              echo
              if [ "$code" = "200" ]; then
                return 0
              fi
              tries=$((tries+1))
              echo "Retry $tries tra 8s…"
              sleep 8
            done
            return 1
          }

          for league in turchia austria belgio danimarca grecia polonia romania svizzera ungheria; do
            echo "==> SOC $league"
            retry "http://localhost:3000/api/fetchResultSoc?league=$league&season=2025-2026" || { echo "FAILED SOC $league"; exit 22; }
            sleep 1
          done

      # Mostra sempre gli ultimi log del server (anche se un curl fallisce)
      - name: Log server Next (tail)
        if: ${{ always() }}
        run: |
          echo "=== tail server.log ==="
          tail -n 200 server.log || echo "server.log non trovato"

      - name: Diagnostica contenuto data e diff
        if: ${{ always() }}
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          find data -maxdepth 3 -type f -name "*.json" -print | sort || true
          echo "--- changed files ---"
          git status --porcelain

      - name: Commit JSON changes (rebase su origin/main)
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data
          if git diff --cached --quiet; then
            echo "Nessuna modifica trovata."
            exit 0
          fi

          git commit -m "update: refresh dati JSON automatico (08:00/09:00 IT)"

          git fetch origin main
          git rebase origin/main || (echo "Rebase fallito, annullo"; git rebase --abort; exit 1)

          git push origin HEAD:main